[build]
  command = "hugo"
  publish = "public"

[context.production]
  command = "hugo"
  [context.production.environment]
    HUGO_VERSION = "0.125.7"
    HUGO_ENV = "production"

[context.branch-deploy]
  command = "hugo -F -b $DEPLOY_PRIME_URL"
  [context.branch-deploy.environment]
    HUGO_VERSION = "0.125.7"

[context.deploy-preview]
  command = "hugo -F -b $DEPLOY_PRIME_URL"
  [context.deploy-preview.environment]
    HUGO_VERSION = "0.125.7"
