---
title: "ESG: ¿El futuro de las Finanzas?"
excerpt: "¿Qué pasaría si Uruguay perdiera el Grado Inversor en su deuda soberana? Este artículo dará algunos lineamientos de sus posibles consecuencias "
date: 2021-12-09

show_post_time: false

author: "Diego Rijos"
location: "Montevideo, Uruguay"
draft: false
layout: single
categories:
  - El Observador
  - Academia Nacional de Economía
  - ESG
  - Finanzas Sostenibles
  - Mercado de Valores
tags:
  - Finanzas Sostenibles
  - Gestión de Deuda
  - ESG

links:
- icon: readme
  icon_pack: fab
  name: Link a la nota en El Observador
  url: https://www.elobservador.com.uy/nota/esg-el-futuro-de-las-finanzas--20211282270
  
- icon: file-download
  icon_pack: fas
  name: Descargar pdf
  url: https://www.scribd.com/document/545788104/2021-12-09-principal-12
---


Las finanzas están cambiando. La integración de factores Sociales, Ambientales y de Gobernanza (ESG por sus siglas en inglés), han ido permeando en las estrategias de inversión por parte de los principales fondos de inversión. La adopción por parte de estos de estrategias que contemplen la sostenibilidad es patente, según la US SIF Foundation en un estudio de 2020, 1 de cada 3 dólares de los activos bajo manejo profesional en Estados Unidos se encuentran atados a algún tipo de estrategia sostenible (US SIF Foundation, 2020). Este cambio no ha sido de un día para el otro, comenzó con la paulatina incorporación de la Responsabilidad Social Empresarial, y ha ido evolucionando hacia la integración de nuevos factores como lo son los pilares ambientales y de gobernanza.

Las estrategias de inversión ESG, se pueden definir como la integración dentro de los objetivos de inversión de consideraciones ambientales, sociales y de gobernanza. Esto genera que a la hora de seleccionar activos financieros los inversores busquen las posibles implicancias que las empresas o gobiernos puedan tener en estos tres pilares. Es así, como los emisores de activos financieros han empezado a tomar en cuenta estos factores a la hora de generar nuevas propuestas de valor o adaptar las ya existentes para incorporarlos. 

Los inversores y calificadoras de riesgo toman estas señales como un compromiso en el largo plazo con la sostenibilidad. Esto por su parte, tanto teórica como empíricamente, mitiga ciertos riesgos en los activos (el más claro problemas derivados por la mala gestión ambiental). Esto vuelve más resiliente a esta clase activos a la hora de navegar en los mercados financieros y aumenta el potencial para generar mayor valor. Según un estudio de Morningstar Manager Research (2020), los fondos con estrategias sostenibles han performado en términos generales mejor que sus pares tradicionales, incluso ante la crisis provocada por la pandemia del Covid-19. Esto también ha puesto en relevancia estos factores en los fondos de pensión, la importancia de tener en cartera este tipo de activos. A nivel global se han ido adhiriendo a este tipo de estrategias fondos de pensión y fondos soberanos, en algunos casos como consecuencia de la regulación mientras que en otros por voluntad propia (Global Sustainable Investment Alliance, 2021). Sin ir más lejos, en Uruguay algunos fondos de pensión se han ido plegando a esta estrategia de invertir tomando en cuenta estos factores, comenzando con Unión Capital AFAP que fue la pionera en plegarse a los principios de inversión responsable (PRI) en 2020. 

Desde el punto de vista de la oferta, en Uruguay se ha comenzado a emitir instrumentos en los últimos años que contemplan algunos de estos factores. El avance de la producción de energía solar permitió que Atlas Renewable Energy emitiera títulos para financiar cerca de 360 millones de dólares mediante dos emisiones (una en 2018 y otra en 2020), siendo la primera emisión verde como tal que tuvo el país. BBVA, en línea con ello, emitió 15 millones de dólares en bonos en febrero de 2021 para poder financiar su cartera de proyectos sostenibles, al igual que marcar el hito de la emisión de un bono temático.  Por su parte, AF Forestal logro colocar una venta de 210.000 toneladas de bonos de carbono, siendo la primera operación que realiza el país en estos activos. La última emisión que realizo TATA S.A. al igual que el préstamo obtenido por esta de parte de BID invest, contenía un fuerte matiz ESG en su prospecto. De esta manera Uruguay no se ha visto ajeno a la ola global de activos sostenibles.

La participación activa de la Ministro de Economía en la COP26, ha mostrado que desde el gobierno se ha ido avanzando en la integración de estos temas en la agenda. En especial respecto al financiamiento necesario para generar estos cambios. En este sentido, la Unidad de Gestión de Deuda, según fuentes oficiales se encuentra estructurando un bono soberano que contenga estos aspectos. Aun no hay información concreta, pero se espera que fuera en la modalidad Sustainability-linked Bond (SLB), y que pone como covenants de las condiciones de repago y tasa el cumplimiento de ciertos KPIs (indicadores de performance) ambientales. De esta manera Uruguay debutaría en el mercado internacional de bonos soberanos sostenibles, siendo el cuarto país latinoamericano en generar una emisión de estas características. Esto permitiría no sólo posicionar al país en términos de sostenibilidad, sino ampliar la base inversora externa en bonos, ya que por sus características puede entrar en algunos de los fondos sostenibles que existen a la fecha.

Este cambio en el paradigma de inversión de las finanzas, puede generar oportunidades para el país, tanto en el sector público como privado. Dado el nuevo impulso por parte del gobierno al mercado de capitales, podría ser una buena oportunidad para poder generar sinergias que permitan la emisión de este tipo de activos en el mercado local. De esta manera, tanto el sector público como privado pueden tener la oportunidad de financiar emprendimientos sostenibles, al igual que dinamizar el mercado de capitales local. Lejos de ser el futuro de las finanzas, la integración ESG es una realidad latente en el mercado, de la que Uruguay no puede ni debe mantenerse ajeno. 

US SIF Foundation. (2020). Report on US Sustainable and Impact Investing Trends. Washington D.C. : USSIF.
Morningstar Manager Research. (2020). Sustainable Funds U.S. Landsccape Report. Sustainable Investing Research. Nueva York: Morningstar.


